### ISSUE TITLE
esphome: needs to run in privileged mode

### ISSUE THREAD

**Issue by domoritz** [truenas/apps#1451]
According to the docs, the container needs to run in privileged mode: https://esphome.io/guides/getting_started_command_line.html. I don't seem to be able to compile anything when it's not.

**Comment by stavros-k** [comment]
Should be fixed by #1453

**Comment by domoritz** [comment]
I was trying to build a package but it looks like the container can't create the cache directory.

```
Installing collected packages: wheel, urllib3, typing-extensions, tqdm, pyyaml, python-dotenv, pyparsing, pycparser, kconfiglib, jsonref, idna, future, colorama, click, charset-normalizer, certifi, annotated-types, requests, pydantic-core, esp-idf-kconfig, cffi, requests-toolbelt, requests-file, pydantic, cryptography, pydantic-settings, idf-component-manager
Successfully installed annotated-types-0.7.0 certifi-2024.12.14 cffi-1.17.1 charset-normalizer-3.4.1 click-8.1.8 colorama-0.4.6 cryptography-41.0.7 esp-idf-kconfig-1.5.0 future-1.0.0 idf-component-manager-2.0.4 idna-3.10 jsonref-1.1.0 kconfiglib-14.1.0 pycparser-2.22 pydantic-2.10.6 pydantic-core-2.27.2 pydantic-settings-2.7.1 pyparsing-3.2.1 python-dotenv-1.0.1 pyyaml-6.0.2 requests-2.32.3 requests-file-2.1.0 requests-toolbelt-1.0.0 tqdm-4.67.1 typing-extensions-4.12.2 urllib3-1.26.20 wheel-0.45.1
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.5") 
-- git rev-parse returned 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32c3
-- Configuring incomplete, errors occurred!
See also "/config/.esphome/build/esphome-web-12ebe0/.pioenvs/esphome-web-12ebe0/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /config/.esphome/platformio/packages/framework-espidf/tools/cmake/build.cmake:548 (message):
  ERROR: Failed to create cache directory: /.cache/Espressif/ComponentManager

Call Stack (most recent call first):
  /config/.esphome/platformio/packages/framework-espidf/tools/cmake/project.cmake:604 (idf_build_process)
  CMakeLists.txt:3 (project)
```

I did apply the `apps` ACL on the dataset for the esphome config. Amy I missing something?

**Comment by FeatherKing** [comment]
@domoritz could you send a gist or something with your esphome yaml build (redacting any secrets) and ill try on my side?

also could you share the permissions on the folders (`ls -la` from outside the container)

i suspect permissions because tests are passing, but those create the directories from scratch each time. Curious that i didnt trigger the cache path either, but i believe we can override that with another env var.

**Comment by stavros-k** [comment]
Try without ACLs first. (ideally with ix-volumes).
I've seen MANY apps that won't work with ACLs sadly

**Comment by domoritz** [comment]
Here is the spec I am building. 

```yaml
substitutions:
  name: esphome-web-12ebe0
  friendly_name: AirGradient
  name_add_mac_suffix: "false"  # Must have quotes around value

  co2_green: '400'
  co2_yellow: '900'
  co2_red: '1500'
  co2_purple: '3000'
  pm_2_5_green: '0'
  pm_2_5_yellow: '10'
  pm_2_5_red: '25'
  pm_2_5_purple: '100'
  voc_green: '100'
  voc_yellow: '150'
  voc_red: '250'
  voc_purple: '400'
  voc_blue: '50'

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXX"

ota:
  platform: esphome


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: 192.168.X.XXX

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-12Ebe0"
    password: "XXXXX"

captive_portal:

dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-one.yaml
  import_full_config: false

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  # pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003_extended_life.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  temp_humidity: github://MallocArray/airgradient_esphome/packages/sensor_sht40.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  display: github://MallocArray/airgradient_esphome/packages/display_sh1106_multi_page.yaml
  led: github://MallocArray/airgradient_esphome/packages/led.yaml
  # led_co2: github://MallocArray/airgradient_esphome/packages/led_co2.yaml
  led_combo: github://MallocArray/airgradient_esphome/packages/led_combo.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  config_button: github://MallocArray/airgradient_esphome/packages/config_button.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true  # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
```

I tried changing to POSIX permissions but still get an error. 

Here are the permissions from outside the container. Note that the directory is mounted as /config inside the container. 

```
$ls -la
total 56
drwxrwxr-x  3 apps apps     8 Jan 24 19:46 .
drwxrwx--- 15 root root    16 Jan 20 10:41 ..
drwxrwxr-x 11 apps apps    12 Jan 27 17:27 .esphome
-rwxrwxr-x  1 apps apps   170 Jan  3 10:28 .gitignore
-rwxrwxr-x  1 apps apps  2517 Jan 24 19:34 esphome-web-12ebe0.yaml
-rwxrwxr-x  1 apps apps  1990 Jan 24 19:33 esphome-web-dcc0f1.yaml
-rwxrwxr-x  1 apps apps 31274 Jan  3 10:33 lilygo.yaml
-rwxrwxr-x  1 apps apps    82 Jan  3 10:28 secrets.yaml
```

**Comment by FeatherKing** [comment]
seems to be related to this specific compiler flow (esp-idf) and non-root
https://github.com/esphome/issues/issues/6520

still thinking about a workaround (without just running as root). the best fix would be to move the folder upstream as mentioned in this issue. maybe ill send them a PR for their docker image.

**Comment by domoritz** [comment]
Ahh, good catch.
