### ISSUE TITLE
How to change the network mode of Home-assistant

### ISSUE THREAD

**Issue by EricNg8801** [truenas/apps#583]
I need to use homekit integration and it required a host network, but the configurtion of truenas scale app has no network option, how can i make it?
![image](https://github.com/user-attachments/assets/99e222cd-4aee-4568-a37a-53d8c90422df)
![image](https://github.com/user-attachments/assets/3f304435-ba68-4753-8e4e-b5943b3e1914)

**Comment by stavros-k** [comment]
You cannot change network mode on apps that have dependencies (eg postgres container).
When the network mode changes to host breaks the internal docker connections.

There are networking options being investigated but are targeted for the next TrueNAS Scale release, (25.04.x).

**Comment by stavros-k** [comment]
See #743

**Comment by TheTrueRandom** [comment]
Also a breaking change to the previous (kubernetes version). [There it was possible to run with host-network](https://github.com/truenas/charts/blob/master/charts/home-assistant/2.0.53/questions.yaml#L116). Would be nice if there was a note. Maybe you can add one now @stavros-k  Right now there is only one note in the [migration guide](https://github.com/truenas/apps/pull/492) which mentions Devices, not network. 

Are there any workarounds? Now that I migrated to electric-eel, which I wouldn't have with such a note, and I don't want to rollback.

**Comment by TheTrueRandom** [comment]
Found a workaround @EricNg8801 

Edit `/mnt/.ix-apps/app_configs/home-assistant/versions/1.3.3/templates/rendered/docker-compose.yaml`
And add `"network_mode": "host",` to `services.home-assistant` section
and add 
```
"ports": [
  {
    "host_ip": "0.0.0.0",
    "mode": "ingress",
    "protocol": "tcp",
    "published": 5432,
    "target": 5432
  }
],
```
to `services.postgres` section. 

Stop the home-assistant app on the trunas UI and then start it again. After home-assistant is started edit the `configuration.yaml` and change `db_url: postgresql://home-assistant:<pw>@postgres:5432/home-assistant?sslmode=disable` to `db_url: postgresql://home-assistant:<pw>@localhost:5432/home-assistant?sslmode=disable`. Then restart home-assistant from the home-assistant UI. 

This process needs to be repeated for each truenas home-assistant app upgrade.

@stavros-k I don't see a reason why this can't be added to the truenas app definition right now. If host-network is chosen there can be an additional note/option to choose the postgres host port. 
Please reopen the issue.

**Comment by EricNg8801** [comment]
> Found a workaround @EricNg8801
> 
> Edit `/mnt/.ix-apps/app_configs/home-assistant/versions/1.3.3/templates/rendered/docker-compose.yaml` And add `"network_mode": "host",` to `services.home-assistant` section and add
> 
> ```
> "ports": [
>   {
>     "host_ip": "0.0.0.0",
>     "mode": "ingress",
>     "protocol": "tcp",
>     "published": 5432,
>     "target": 5432
>   }
> ],
> ```
> 
> to `services.postgres` section.
> 
> Stop the home-assistant app on the trunas UI and then start it again. After home-assistant is started edit the `configuration.yaml` and change `db_url: postgresql://home-assistant:<pw>@postgres:5432/home-assistant?sslmode=disable` to `db_url: postgresql://home-assistant:<pw>@localhost:5432/home-assistant?sslmode=disable`. Then restart home-assistant from the home-assistant UI.
> 
> This process needs to be repeated for each truenas home-assistant app upgrade.
> 
> @stavros-k I don't see a reason why this can't be added to the truenas app definition right now. If host-network is chosen there can be an additional note/option to choose the postgres host port. Please reopen the issue.

thx for reply, but the yaml file mess me up, would you mind share urs for reference？ i can't local the possition i need to add "ports": xxxxx
![image](https://github.com/user-attachments/assets/55f34269-429e-4fa1-942c-e9fac7d33959)

**Comment by TheTrueRandom** [comment]
can just put it to a json formatter, then it's easy to find. The formatted json will work just as fine

**Comment by EricNg8801** [comment]
thx. dude, i've tried but the homekit still doesn't work, no QR code in Notification but 2 error msg. do you have any idea ?
[cid:9d4d0229-abe5-4190-9278-579fc13904f8][cid:e70662c7-4f28-4baa-a43a-d4978562721c][cid:d907004e-cabc-469b-85d2-81d7e410a2ee]

________________________________

**Comment by EricNg8801** [comment]
otherwise, after i add the code you gave, my ha still assist with (truenas ip):8123, is that correct?

________________________________

**Comment by Stonelinks** [comment]
This was affecting me as well, and understand the restrictions @stavros-k pointed out. But yeah the host networking option is pretty essential for HA to operate in general - without it you can't discover any devices on your home's network. Basically everything was impossible to set up on a fresh install of truenas + home assistant without this thread.

Just wanna add when editing the docker compose file, you can change the entrypoint of `init` to `/bin/echo` or something, which at least allows you to restart home assistant without needing to go back and edit the DB URL in `configuration.yaml`

**Comment by EricNg8801** [comment]
But home bridge can't load after adding the code to change the network mode😫

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Delivator** [comment]
I'm so confused. How has this just been closed without any more coment on possible fixes? Home-Assistant is, as @Stonelinks mention, completely useless like it is now. No device on the network is discovered?!

**Comment by stuhad** [comment]
Does this workaround still work? 

It had been working fine for a few months, but have just tried upgrading (HA 2025.2.3) and re-editing the docker-compose (version 1.4.24)
home-assistant starts, but getting a lot of errors that devices can't be setup

TrueNAS ElectricEel-24.10.2 

I might have stuffed something up, but I can't see where

**Comment by Delivator** [comment]
I ended up using a dedicated raspberry pi, because it also allows me to install HA addons.

**Comment by Stonelinks** [comment]
unknown - i have not (and will not) upgrade HA on truenas until this issue
is resolved

**Comment by TheTrueRandom** [comment]
Workaround still works on 1.4.23. Haven't tried 1.4.24 yet.

**Comment by parkan** [comment]
what about just using the default sqlite backend instead of a custom separate postgres container? in the absence of multiple writers sqlite is just as if not more performant than postgres and creates fewer headaches

this would allow simply using host network, sidestepping any complex orchestration issues

**Comment by TheTrueRandom** [comment]
> what about just using the default sqlite backend instead of a custom separate postgres container? 

Migrating the DB backend of an existing homeassistant installation is no straightforward task.

**Comment by TheTrueRandom** [comment]
> There are networking options being investigated but are targeted for the next TrueNAS Scale release, (25.04.x).

@stavros-k  what's the state there? I'm on 25.04 an it's still not working. Please reopen this issue also as long as it does not have a resolution.

**Comment by stavros-k** [comment]
> > There are networking options being investigated but are targeted for the next TrueNAS Scale release, (25.04.x).
> 
> [@stavros-k](https://github.com/stavros-k) what's the state there? I'm on 25.04 an it's still not working. Please reopen this issue also as long as it does not have a resolution.

https://github.com/truenas/apps/issues/583#issuecomment-2452158343

**Comment by Stonelinks** [comment]
I’ve been upgrading every single time I have the chance in this work around is still valid.

**Comment by kidroca** [comment]
> > what about just using the default sqlite backend instead of a custom separate postgres container?
> 
> Migrating the DB backend of an existing homeassistant installation is no straightforward task.

Yeah, but sqlite is the default - I had the opposite problem. I migrated from HA in VM to TrueNAS App, and had no idea it won't work out of the box.

I installed HA and used the built in restore from backup, which got stuck. It took some time to notice the configuration.yaml was overwritten to use the Postgres database 

For me it would be better to stick with sqlite, HA docs themselves say it's more than sufficient 
This would allow for host mode

Ideally I would like to expose the container directly on my LAN with a dedicated IP

**Comment by parkan** [comment]
> > what about just using the default sqlite backend instead of a custom separate postgres container?
> 
> Migrating the DB backend of an existing homeassistant installation is no straightforward task.

I've had to do this a few times for different systems (as much as I love postgres it is... not the best choice for smaller projects a lot of the time) and in the end using https://github.com/caiiiycuk/postgresql-to-sqlite on a dump has been completely trouble-free IME; the only thing to pay attention to is selecting the right value for `-t` (timestamp conversion) to match what the HA sqlite schema expects, otherwise it kinda Just Works

The more manual process (https://community.home-assistant.io/t/postgresql-to-sqlite-migration-moving-back-to-sqlite/764151) is certainly nontrivial and harder to automate, but to be fair it seems that a decent number of users have still undertaken it and are happier with the sqlite setup.

I appreciate the pressures of maintaining backwards compatibility for existing users but to me this feels like a one-time pain cost for significantly reduced complexity from here on out.

**Comment by TheTrueRandom** [comment]
I decided to uninstall the official home-assistant app because of this issue. Quite a pity, if I remember correctly a while back the truenas team removed truecharts because apparently they add so many breaking changes, however the only place I see breaking changes all the time is truenas itself. Probably the best to use the official apps as little as possible and stay to simple docker(compose). 

If someone wants to do the same, here is what I did.
- migrate to sqlite: https://community.home-assistant.io/t/postgresql-to-sqlite-migration-moving-back-to-sqlite/764151/9  (not necessarily needed, otherwise a postgres container would need to be added in the next step, referencing the existing data)
- stop the homeassistant app
- add a new custom app with docker-compose, I copied the homeassistant container of  the official app, which looks something like this. Probably can be minified but it works for now. Make sure `network_mode: host` is set.
- before starting the new app, make sure to remove `recorder.db_url` from the homeassistant configuration.yaml, so sqlite will be used instead of postgres 
```
services:
  home-assistant:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - NET_BIND_SERVICE
      - NET_RAW
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    environment:
      GID: '568'
      GROUP_ID: '568'
      NVIDIA_VISIBLE_DEVICES: void
      PGID: '568'
      PUID: '568'
      TZ: Europe/Berlin
      UID: '568'
      UMASK: '002'
      UMASK_SET: '002'
      USER_ID: '568'
    group_add:
      - '568'
    image: homeassistant/home-assistant:2025.5.1
    network_mode: host
    platform: linux/amd64
    privileged: False
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    stdin_open: False
    tty: False
    user: '0:0'
    volumes:
      - read_only: False
        source: /hostpath/to/homeassistant/config
        target: /config
        type: bind

```

**Comment by lcs-crr** [comment]
>  There are networking options being investigated but are targeted for the next TrueNAS Scale release, (25.04.x).

Have these options not made it to the release, or does it have to be implemented in HA?

**Comment by parkan** [comment]
for anyone looking, here's a custom app compose that delivers a working HA with zeroconf (device discovery) and HACS https://gist.github.com/parkan/a729c8ee0928a8793d129f1ae3031eb8

note that you will need to disable the trueNAS mDNS, which has never worked for me in the first place:

`sudo systemctl disable --now avahi-daemon avahi-daemon.socket`

edit: oops missed the manifest above, will adopt some changes from that
